// <auto-generated />
using System;
using ControleFinanceiro.Dados.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleFinanceiro.Dados.Migrations
{
    [DbContext(typeof(ControleFinanceiroDbContext))]
    [Migration("20240505200109_ajustandoFKs")]
    partial class ajustandoFKs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.Categorias", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<bool>("CategoriaDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("CategoriaDeletado")
                        .HasColumnType("bit");

                    b.Property<string>("CategoriaDescricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategoriaNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.DespesaParcelas", b =>
                {
                    b.Property<int>("DespesaParcelaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DespesaParcelaId"));

                    b.Property<int>("DespesaId")
                        .HasColumnType("int");

                    b.Property<bool>("DespesaParcelaDeletado")
                        .HasColumnType("bit");

                    b.Property<double?>("DespesaValor")
                        .HasColumnType("float");

                    b.Property<int>("StatusDespesas")
                        .HasColumnType("int");

                    b.HasKey("DespesaParcelaId");

                    b.HasIndex("DespesaId");

                    b.ToTable("DespesaParcelas");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.Despesas", b =>
                {
                    b.Property<int>("DespesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DespesaId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DespesaDataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DespesaDeletado")
                        .HasColumnType("bit");

                    b.Property<string>("DespesaDescricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DespesaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DespesaQuantidadeParcelas")
                        .HasColumnType("int");

                    b.Property<DateTime>("DespesasDataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoValor")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DespesaId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.FormasPagamento", b =>
                {
                    b.Property<int>("FormaPagamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormaPagamentoId"));

                    b.Property<string>("FormaPagamentoNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FormaPagamentoId");

                    b.ToTable("FormasPagamento");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.ReceitaParcelas", b =>
                {
                    b.Property<int>("ReceitaParcelaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceitaParcelaId"));

                    b.Property<int>("ReceitaId")
                        .HasColumnType("int");

                    b.Property<bool>("ReceitaParcelaDeletado")
                        .HasColumnType("bit");

                    b.Property<double>("ReceitaValor")
                        .HasColumnType("float");

                    b.Property<int>("StatusDespesas")
                        .HasColumnType("int");

                    b.HasKey("ReceitaParcelaId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ReceitaParcelas");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.Receitas", b =>
                {
                    b.Property<int>("ReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceitaId"));

                    b.Property<DateTime>("ReceitaDataInclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceitaDataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ReceitaDeletado")
                        .HasColumnType("bit");

                    b.Property<string>("ReceitaDescricao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceitaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReceitaQuantidadeParcelas")
                        .HasColumnType("int");

                    b.Property<int>("TipoValor")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReceitaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.Usuarios", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.UsuariosOperacoesLog", b =>
                {
                    b.Property<int>("UsuarioOperacaoLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioOperacaoLogId"));

                    b.Property<bool>("Error")
                        .HasColumnType("bit");

                    b.Property<string>("NomeController")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeMetodo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeOperacao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("OperacaoData")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioOperacaoLogId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosOperacoesLog");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.Categorias", b =>
                {
                    b.HasOne("ControleFinanceiro.Dominio.Entities.Usuarios", "Usuarios")
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.DespesaParcelas", b =>
                {
                    b.HasOne("ControleFinanceiro.Dominio.Entities.Despesas", "Despesas")
                        .WithMany("DespesaParcelas")
                        .HasForeignKey("DespesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.Despesas", b =>
                {
                    b.HasOne("ControleFinanceiro.Dominio.Entities.Categorias", "Categorias")
                        .WithMany("Despesas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFinanceiro.Dominio.Entities.FormasPagamento", "FormasPagamento")
                        .WithMany("Despesas")
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFinanceiro.Dominio.Entities.Usuarios", "Usuarios")
                        .WithMany("Despesas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorias");

                    b.Navigation("FormasPagamento");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.ReceitaParcelas", b =>
                {
                    b.HasOne("ControleFinanceiro.Dominio.Entities.Receitas", "Receitas")
                        .WithMany()
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.Receitas", b =>
                {
                    b.HasOne("ControleFinanceiro.Dominio.Entities.Usuarios", "Usuarios")
                        .WithMany("Receitas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.UsuariosOperacoesLog", b =>
                {
                    b.HasOne("ControleFinanceiro.Dominio.Entities.Usuarios", "Usuarios")
                        .WithMany("UsuariosOperacoesLog")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.Categorias", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.Despesas", b =>
                {
                    b.Navigation("DespesaParcelas");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.FormasPagamento", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("ControleFinanceiro.Dominio.Entities.Usuarios", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Despesas");

                    b.Navigation("Receitas");

                    b.Navigation("UsuariosOperacoesLog");
                });
#pragma warning restore 612, 618
        }
    }
}
